### PR TITLE
Allow DisposedManaged & DisposeUnmanaged to be virtual

### PR DESCRIPTION
**Pull request by jasonwoods-7**
Changing OpCode from Call to Callvirt when DisposeManaged/DisposeUnmanaged functions are marked as virtual.

### CODE REVIEW

**Comment by jasonwoods-7** [comment]
Also, quick question.  What is the reason for skipping weaving on an abstract class? Ref: [ModuleWeaver.cs](https://github.com/Fody/Janitor/blob/master/Fody/ModuleWeaver.cs#L32)

**Comment by SimonCropp** [comment]
before i answer what is your use case for wanting this change?

**Comment by jasonwoods-7** [comment]
Ok, what I have is something like this

``` c#
public abstract class AbstractFoo : IDisposable
{
  readonly IDisposable _someField;

  protected AbstractFoo(IDisposable someField)
  {
    _someField = someField;
  }

  protected virtual void DisposeManaged()
  {
    _someField.Dispose();
  }

  public void Dispose()
  {
    // Fody will fill this in.
  }

  // ... impl ...
}

public class DerivedFooA : AbstractFoo
{
  public DerivedFooA(IDisposable someField)
    : base(someField)
  {
  }

  // ... impl ...
}

public class DerivedFooB : AbstractFoo
{
  readonly IDisposable _someOtherField;

  public DerivedFooB(IDisposable someField, IDisposable someOtherField)
    : base(someField)
  {
    _someOtherField = someOtherField;
  }

  protected override void DisposeManaged()
  {
    _someOtherField.Dispose();
    base.DisposeManaged();
  }

  // ... impl ...
}
```

Where the abstract class is in a Core assembly and the derived classes are used in separate assemblies for different projects.

The only reason I found this issue today was that I was looking over our code coverage results from our build and I saw that the Dispose methods were not being called.  I think I originally wrote the classes following the standard .Net disposal pattern (with a `protected virtual void Dispose(bool disposing)` method), but when I found Fody, I added Janitor to our Core assembly to simplify the code.

If there's another way to achieve this, I'm open to suggestions.

**Comment by SimonCropp** [comment]
ok your use case is reasonable. so happy to merge. 

before i merge... re the abstract check. that is prob a copy paste bug. did u want to have a go at a PR for that? or fix it in this PR?

**Comment by jasonwoods-7** [comment]
I'll just use this PR.  I just pushed the change up.

**Comment by SimonCropp** [comment]
this should now be on nuget

**Pull request merged**
